# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.investing.com/")
    self.driver.set_window_size(1365, 880)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"search-section\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"search-section\"]").send_keys("bbas3")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"search-section\"]").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.LINK_TEXT, "Currencies")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".js-inner-all-results-quote-item:nth-child(1) > .second").click()
    element = self.driver.find_element(By.LINK_TEXT, "Unlock Value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
