# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchroutine2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchroutine2(self):
    self.driver.get("https://www.investing.com/")
    self.driver.set_window_size(1365, 880)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"search-section\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"search-section\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"search-section\"]").send_keys("bbas3")
    self.driver.find_element(By.CSS_SELECTOR, ".mainSearch_symbol__YMUvc").click()
    element = self.driver.find_element(By.LINK_TEXT, "Pre-Market")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
