# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestbb():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testbb(self):
    self.driver.get("https://statusinvest.com.br/acoes")
    self.driver.set_window_size(550, 691)
    element = self.driver.find_element(By.CSS_SELECTOR, "a > .image")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,1224)")
    self.driver.find_element(By.CSS_SELECTOR, ".pl-1:nth-child(1) tr:nth-child(1) .d-block:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".special").click()
    self.driver.find_element(By.CSS_SELECTOR, ".special").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-special > .info:nth-child(4)").click()
    self.driver.execute_script("window.scrollTo(0,2319)")
    self.driver.execute_script("window.scrollTo(0,2798)")
    self.driver.find_element(By.CSS_SELECTOR, "#main-2 > .container:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) > .d-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".indicators:nth-child(1) .w-50:nth-child(2) > div > .d-flex:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) .w-50:nth-child(2) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) .w-50:nth-child(3) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) > .d-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) > .d-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) .w-50:nth-child(6) > div").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".w-50:nth-child(11) > div > .term-indicator-link")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(1) > .d-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-2 > .container:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-2 > .container:nth-child(4)").click()
    self.driver.find_element(By.ID, "main-2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-2 > .container:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .indicators:nth-child(5) > .d-block").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-2 > .container:nth-child(4)").click()
    self.driver.execute_script("window.scrollTo(0,3978)")
    self.driver.execute_script("window.scrollTo(0,5710)")
  
